eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/microservices
  zipkin:
    base-url: http://zipkin:9411
